language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source $PREFER_LOWEST

script:
  - ./bin/phpspec run --format=dot
  - ./bin/behat
