name: Tests

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        composer-stability: [ 'prefer-lowest', 'prefer-stable' ]

    name: PHP ${{ matrix.php-versions }} - ${{ matrix.composer-stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-source --no-interaction --${{ matrix.composer-stability }}

      - name: Run phpspec tests
        run: ./bin/phpspec run --format=dot

      - name: Run behat tests
        run: ./bin/behat
